ec:
  __dictpath__: ec
  __doc__: null
  checkpoint: drl/checkpoints/mc_20_10_0/21
  drl_config: drl/configs/dev.yml
  ept1:
    __dictpath__: ec.ept1
    __doc__: null
    max_num_sensors: 30
    min_num_sensors: 20
    num_targets: 10
    solvers:
    - drl
    - random
    test_size: 10
  ept2:
    __dictpath__: ec.ept2
    __doc__: null
    k_bit: 20000000
    max_prob: 1
    min_prob: 0.1
    num_sensors: 20
    num_targets: 10
    solvers:
    - drl
    - random
    step: 0.1
    test_size: 10
  wrsn_config: drl/configs/dev.yml
