ec:
  __dictpath__: ec
  __doc__: null
  checkpoint: model002/checkpoints/mc_20_10_0/21
  drl_config: model002/configs/mc_20_10_2_small.yml
  ept1:
    __dictpath__: ec.ept1
    __doc__: null
    k_bit: 8000000
    max_num_sensors: 30
    min_num_sensors: 20
    num_targets: 10
    solvers:
    - model002
    - random
    test_size: 2
  ept2:
    __dictpath__: ec.ept2
    __doc__: null
    k_bit: 20000000
    max_prob: 1
    min_prob: 0.1
    num_sensors: 20
    num_targets: 10
    solvers:
    - model002
    - random
    step: 0.1
    test_size: 2
  wrsn_config: model002/configs/mc_20_10_2_small.yml
